import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { PGlite } from "@electric-sql/pglite";
import { query, useDriver as setDriver, type Transaction } from "../src/lib/db";
import type { User } from "../src/lib/auth";
import { canSupport, isStaff, setRole } from "../src/lib/staff";
import { createSupport, readSupport, replySupport, actSupport, setSupportAccess } from "../src/lib/supportStore";
import { moderatorRewards, currentRewardMonth } from "../src/lib/moderatorRewards";
import { moderatorBoard, deductModerator, moderatorDeductions } from "../src/lib/moderatorStore";
const pg = new PGlite();
const transaction: Transaction = statements => pg.transaction(async tx => {
  const rows: Record<string, unknown>[][] = [];
  for (const s of statements) rows.push((await tx.query(s.text,s.params ?? [])).rows as Record<string, unknown>[]);
  return rows;
});
setDriver(async (text, params=[]) => (await pg.query(text,params)).rows as never, transaction);
for (const [id, role] of [['owner','owner'],['lead','lead'],['admin','staff'],['modA','moderator'],['modB','moderator'],['player','player']]) await query("insert into users(steam_id,persona,role,discord_id) values($1,$1,$2,$1)",[id,role]);
const user = async (id:string) => (await query<User>("select * from users where steam_id=$1",[id]))[0];
const owner=await user('owner'), lead=await user('lead'), admin=await user('admin'), a=await user('modA'), b=await user('modB'), player=await user('player');
assert.equal(canSupport(a),true); assert.equal(isStaff(a),false);
assert.equal(await setRole(lead,'player','moderator'),null);
assert.ok(await setRole(a,'modA','owner'));
await setRole(owner,'player','player');
const ticket = async (type='question') => { const id=randomUUID(); assert.equal(await createSupport(player,{id,type,cluster:'Solo',body:'Need advice',details:{}}),id); return id; };
const q=await ticket();
await setSupportAccess(owner,'admin','*','question',true);
assert.equal(await readSupport(admin,q),null,"ordinary admins cannot take question support");
assert.ok(await readSupport(a,q));
assert.equal(await readSupport(a,await ticket('general')),null);
assert.equal(await readSupport(a,await ticket('bm_shirt')),null);
assert.equal(await actSupport(a,q,'claim','',randomUUID()),true);
assert.equal(await replySupport(a,q,randomUUID(),'Internal review',true),true);
assert.equal(await actSupport(a,q,'close','Resolved',randomUUID()),true);
assert.equal((await query('select * from moderator_credits')).length,0,"private notes/control messages earn no credit");
assert.equal(await actSupport(owner,q,'reopen','',randomUUID()),true);
assert.equal(await replySupport(a,q,randomUUID(),'Here is the fix'),true);
assert.equal(await actSupport(b,q,'close','Resolved',randomUUID()),true);
assert.equal((await query<{moderator:string}>('select * from moderator_credits'))[0].moderator,'modA',"closer without an answer cannot take credit from the answering assignee");
assert.equal(await actSupport(owner,q,'reopen','',randomUUID()),true);
assert.equal(await replySupport(b,q,randomUUID(),'Follow-up answer'),true);
assert.equal(await actSupport(b,q,'close','Resolved again',randomUUID()),true);
assert.equal((await query('select * from moderator_credits')).length,1,"reopened tickets do not farm credits");
const q2=await ticket(); await replySupport(b,q2,randomUUID(),'Public answer'); await actSupport(b,q2,'close','Done',randomUUID());
let board=await moderatorBoard('modA',currentRewardMonth());
assert.equal(board.length,1); assert.equal(board[0].bonus,0); assert.equal(board[0].tied,true,"self-only board does not create a false winner");
const q3=await ticket(); await replySupport(b,q3,randomUUID(),'Public answer'); await actSupport(b,q3,'close','Done',randomUUID());
board=await moderatorBoard('modA',currentRewardMonth()); assert.equal(board[0].winner,false);
const top=await moderatorBoard('modB',currentRewardMonth()); assert.equal(top[0].bonus,75);
assert.deepEqual(await moderatorBoard('admin',currentRewardMonth()),[]);
const deduction={id:randomUUID(),moderator:'modB',month:currentRewardMonth(),points:5,severity:'normal',reason:'Incorrect advice, ticket reference'};
assert.equal(await deductModerator('admin',deduction),false);
assert.equal(await deductModerator('lead',deduction),true);
assert.equal(await deductModerator('lead',deduction),true);
assert.equal(await deductModerator('lead',{...deduction,points:6}),false,"retry UUID cannot be reused for changed deductions");
assert.equal((await moderatorDeductions('modB',deduction.month)).length,1);
assert.equal((await moderatorDeductions('modA',deduction.month)).length,0);
assert.equal((await moderatorBoard('modB',deduction.month))[0].tickets,0);
assert.equal(await deductModerator('lead',{...deduction,id:randomUUID(),points:11}),false);
assert.equal(await deductModerator('lead',{...deduction,id:randomUUID(),points:11,severity:'major'}),true);
await query("update users set role='player' where steam_id='modA'");
assert.equal(await readSupport(a,q),null,"stale moderator sessions lose ticket access immediately");
await query("update users set role='player' where steam_id='lead'");
assert.equal(await deductModerator('lead',{...deduction,id:randomUUID()}),false);
for (const [n,credit,days] of [[60,0,0],[61,50,0],[100,50,0],[101,125,0],[400,125,0],[401,125,28]]) { const result=moderatorRewards(n); assert.equal(result.storeCredit,credit); assert.equal(result.toaaDays,days); }
assert.equal(moderatorRewards(106,5).storeCredit,125); assert.equal(moderatorRewards(100,200).tickets,0);
assert.equal(moderatorRewards(29).inactivityReview,true); assert.equal(moderatorRewards(30).inactivityReview,false); assert.equal(moderatorRewards(45).targetMet,true);
await pg.close();
console.log('Moderators: question-only ACL, fresh roles, one credit per answered resolution, reopening, monthly tiers, bonus ties, private deductions and retry idempotency passed.');
