import assert from "node:assert/strict";
import {PGlite} from "@electric-sql/pglite";
import {query,useDriver as configureDriver,type Transaction} from "../src/lib/db";
import {draftRules,publishRules,liveRules,staffRules} from "../src/lib/rulesStore";
import {parseRules,rulesRaw,rulesSummary} from "../src/lib/rulesParse";
import {publicProfileForDiscord,saveAccountProfile,profileInput} from "../src/lib/account-profile";
import {parseHof,saveHof,publishedHof} from "../src/lib/hofStore";
import type {User} from "../src/lib/auth";
import {tributeColor,rosterHistory} from "../src/lib/hofTribute";
import seed from "../src/data/rules.json";
import recovery from "../src/data/hofRecovery.json";
import hof from "../src/data/hofMembers.json";
const pg=new PGlite();
const tx:Transaction=statements=>pg.transaction(async db=>{
  const rows:Record<string,unknown>[][]=[];
  for(const s of statements) rows.push((await db.query(s.text,s.params??[])).rows as Record<string,unknown>[]);
  return rows;
});
configureDriver(async(text,params=[]) => (await pg.query(text,params)).rows as never,tx);
const staff={steam_id:"76561199000000001",role:"staff"} as User;
const lead={steam_id:"76561199000000002",role:"lead"} as User;
const player={steam_id:"76561199000000003",role:"player"} as User;
for(const user of [staff,lead,player]) await query("insert into users(steam_id,role) values($1,$2)",[user.steam_id,user.role]);
assert.equal((await liveRules()).id,"seed");
const raw="# Test rules\n- Cycling is allowed after Day 5 on 3/6 Man.\nDeclare all cyclers in the HOF application.\n- No private evidence in public rules.";
const doc=parseRules(raw);
assert.deepEqual(parseRules(rulesRaw(doc)),doc);
assert.match(doc.sections[0].rules[0],/Day 5.*3\/6 Man/);
assert.match(doc.sections[0].rules[0],/Declare all cyclers/);
assert.equal(rulesSummary(doc)[0].count,2);
assert.throws(()=>parseRules("")); assert.throws(()=>parseRules("a".repeat(60001)));
assert.equal(await draftRules(player,raw),null);
const one=(await draftRules(staff,raw))!;
assert.ok(one); assert.equal((await liveRules()).id,"seed","previews do not publish");
assert.equal((await staffRules(player)).length,0);
assert.equal(await publishRules(staff,one,"seed"),false);
assert.equal(await publishRules(lead,one,"seed"),true);
const two=(await draftRules(staff,"# Updated\n- A second rule."))!;
assert.equal(await publishRules(lead,two,"seed"),false,"stale editors cannot overwrite newer rules");
await query("update users set role='player' where steam_id=$1",[lead.steam_id]);
assert.equal(await publishRules(lead,two,one),false,"fresh demotion blocks publication");
await query("update users set role='lead' where steam_id=$1",[lead.steam_id]);
assert.equal(await publishRules(lead,two,one),true);
assert.equal(await publishRules(lead,one,two),true,"verified prior versions can be restored");
assert.equal((await query("select * from rules_publish_audit")).length,3);
assert.equal((await query<{raw:string}>("select raw from rules_revisions where id=$1",[one]))[0].raw,raw,"immutable original remains intact");
const discord="123456789123456789";
await query("update users set discord_id=$1 where steam_id=$2",[discord,player.steam_id]);
const profile=await saveAccountProfile(player.steam_id,profileInput("Bio","teal",true,false));
assert.equal(await publicProfileForDiscord(discord),null,"public account alone does not disclose its Discord association");
await saveAccountProfile(player.steam_id,profileInput("Bio","teal",true,true));
assert.equal((await publicProfileForDiscord(discord))?.id,profile.id);
assert.equal(await publicProfileForDiscord("999999999999999999"),null,"no name guessing");
await saveAccountProfile(player.steam_id,profileInput("Bio","teal",false,true));
assert.equal(await publicProfileForDiscord(discord),null,"unpublishing withdraws HOF discovery");
assert.equal(tributeColor("Test tribe"),tributeColor("test tribe"));
assert.ok(!rosterHistory(hof.winners[0],hof.winners).some(w=>w.id===hof.winners[0].id));
const form=new FormData();
for(const [k,v] of Object.entries({id:crypto.randomUUID(),tribe:"Test tribe",season:"10",cluster:"Solo",date:"2026-10-03",art:"/art/ark/hall.jpg",members:`Survivor | ${discord}`,signature:"A final stand",score:"123456",raids:"0"})) form.set(k,v);
assert.equal(parseHof(form)?.wipeStats?.score,123456);
assert.equal(parseHof(form)?.wipeStats?.raids,0,"zero differs from unavailable");
const winner=parseHof(form)!;
assert.equal(await saveHof(lead,winner,true),false,"stats need evidence before they can be saved");
const privateEvidence="Private support proof 76561199000000003";
assert.equal(await saveHof(lead,winner,true,privateEvidence),true);
assert.ok(!JSON.stringify(await publishedHof()).includes(privateEvidence),"private evidence never enters the public winner DTO");
assert.equal((await query<{evidence:string}>("select evidence from hof_audit where entry_id=$1",[winner.id]))[0].evidence,privateEvidence);
form.set("score","-1");assert.equal(parseHof(form),null);
form.set("score",""); form.set("signature","76561199000000001");assert.equal(parseHof(form),null);
assert.equal(seed.sources.length,12); assert.ok(seed.sections.some(s=>s.rules.some(r=>/24 hours on 100x/.test(r))));
assert.ok(seed.sections.some(s=>s.rules.some(r=>/maximum limit on solos is 2 DPS Dinos/.test(r))));
for(const candidate of recovery.candidates) {
 assert.deepEqual(Object.keys(candidate).sort(),["announcement","matches","observedAt","observedScore","observedRank"].sort());
 assert.ok(hof.winners.some(w=>w.id===candidate.announcement));
 assert.ok(Number.isSafeInteger(candidate.observedScore) && candidate.observedScore>=0);
}
assert.ok(seed.sections.some(s=>s.rules.some(r=>/win the season in which/.test(r))));
assert.ok(seed.sections.some(s=>s.rules.some(r=>/September 25, 2026/.test(r))));
await pg.close(); console.log("Rules permissions, immutable drafts, summary/full text, publication conflicts/restoration, HOF facts and opt-in identity links passed.");
